[package]
name = "transactions-engine"
description = "Transactions engine"
version = "0.1.0"
edition = "2018"
authors = ["Fred Morcos <fm@fredmorcos.com>"]
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
